name: Deploy (apt-get)

on:
  workflow_dispatch:
    inputs:
      tag-name:
        type: string
        description: 'Tag Name:'
        required: true

jobs:
  checkout:
    name: Test GPG Key
    runs-on: ubuntu-latest

    steps:
    - name: Import GPG key
      run: echo -n "${{ secrets.GPG_KEY_SIGN }}" | base64 --decode | gpg --import --passphrase ${{ secrets.GPG_KEY_PASSPHRASE }} --batch
