name: Deploy (apt-get)

on:
  workflow_dispatch:
    inputs:
      tag-name:
        type: string
        description: 'Tag Name:'
        required: true

jobs:
  checkout:
    name: Test GPG Key
    runs-on: ubuntu-latest

    steps:
    - name: List Contents
      run: ls -la ~/.gnupg/

    - name: Prepare GPG
      run: |
       echo "allow-loopback-pinentry" >> ~/.gnupg/gpg-agent.conf
       gpgconf --reload gpg-agent

    - name: Import GPG key
      run: echo -n "${{ secrets.GPG_KEY_SIGN }}" | base64 --decode | gpg --import
